export const REQUEST_ADD_TO_CART = "REQUEST_ADD_TO_CART";
export const ADD_TO_CART = "ADD_TO_CART";

export const REQUEST_REMOVE_CART_ITEM = "REQUEST_REMOVE_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const REQUEST_SAVE_SHIPPING_INFO = "REQUEST_SAVE_SHIPPING_INFO";

export const CLEAR_CART_DATA = "CLEAR_CART_DATA";
