
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const SHOW_ORDER_REQUEST = 'SHOW_ORDER_REQUEST';
export const SHOW_ORDER_SUCCESS = 'SHOW_ORDER_SUCCESS';
export const SHOW_ORDER_FAIL = 'SHOW_ORDER_FAIL';

export const SINGLE_ORDER_REQUEST = 'SINGLE_ORDER_REQUEST';
export const SINGLE_ORDER_SUCCESS = 'SINGLE_ORDER_SUCCESS';
export const SINGLE_ORDER_FAIL = 'SINGLE_ORDER_FAIL';


export const CLEAR_ERROR = 'CLEAR_ERROR';
