export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"; 

export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL";

export const ADMIN_ALL_PRODUCTS_REQUEST = "ADMIN_ALL_PRODUCTS_REQUEST";
export const ADMIN_ALL_PRODUCTS_SUCCESS = "ADMIN_ALL_PRODUCTS_SUCCESS"
export const ADMIN_ALL_PRODUCTS_FAIL = "ADMIN_ALL_PRODUCTS_FAIL"

export const ADMIN_ADD_PRODUCT_REQUEST = "ADMIN_ADD_PRODUCT_REQUEST"
export const ADMIN_ADD_PRODUCT_SUCCESS = "ADMIN_ADD_PRODUCT_SUCCESS"
export const ADMIN_ADD_PRODUCT_FAIL = "ADMIN_ADD_PRODUCT_FAIL"

export const SUBMIT_REVIEW_REQUEST = "SUBMIT_REVIEW_REQUEST";
export const SUBMIT_REVIEW_SUCCESS = "SUBMIT_REVIEW_SUCCESS";
export const SUBMIT_REVIEW_FAIL = "SUBMIT_REVIEW_FAIL";
export const CLEAR_REVIEW_STATUS = "CLEAR_REVIEW_STATUS";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";


export const CLEAR_ERROR = "CLEAR_ERROR";