

//create order  

### 
POST http://localhost:8080/api/v1/order 
content-type: application/json

{
  "shippingInfo":{
    "address": "33 Avedddnu Street ",
    "city": "Berlin",
    "phoneNo": "555-55555-55",
    "postalCode": "544-44",
    "country": "Germany"
    },
  "orderItems": [
      {
      "name": "Apple  2 computer",
      "quantity": 3,
      "image": "http://cloud.google.com",
      "price": 3330.00,
      "product": "60365b55d99aa80021e4824a"
      }
  ],
  "paymentInfo": {
    "id":"60365b55d99aa80021e4824a",
    "status": "Succeeded"
  },
  "itemsPrice": 33300.00,
  "taxPrice": 132.00,
  "shippingPrice": 22.00,
  "totalPrice": 3333.00,
  "orderStatus": "Delivered"

}

###
GET http://localhost:8080/api/v1/orders


###
GET http://localhost:8080/api/v1/order/603945d692843305c4067311

###
GET http://localhost:8080/api/v1/admin/orders

###
PUT http://localhost:8080/api/v1/admin/orders/603945d692843305c4067311
content-type: application/json

{
  "order": "Delivered"
}

###
DELETE http://localhost:8080/api/v1/admin/orders/603945d692843305c4067311

