

GET http://localhost:8080/api/v1/products


###

GET http://localhost:8080/api/v1/products?keyword=Torem&price[gte]=1&price[lte]=333

###

POST http://localhost:8080/api/v1/products/
content-type: application/json



{
  "name": "Torem and mol",
  "price": "33",
  "description": "lorem ipsum dolor sir emmet",
  "ratings": "333",
  "images": [
      {
          "public_id": "http://localhost:8080/jfdsjfjsdfjsdjfjsdfj",
          "url": "http://localhost:8080/fjdsfjdfj"
      }
  ],
  "category": "Laptop",
  "seller": "Johny",
  "stock": 999,
  "reviews": []

}

###

GET http://localhost:8080/api/v1/products/6034e701c84fd9012c3efbd


###

PUT http://localhost:8080/api/v1/admin/products/6033df5f39385b07401a0f80
content-type: application/json

{
  "name": "222Lem ",
  "price": "12223",
  "description": "lorem 2222ipsum dolor sir4444444444mmet worsssssddddddk",
  "ratings": "3223",
  "images": [
      {
          "public_id": "http://localhost:8080/jfdsjfjsdfjsdjfjsdfj",
          "url": "http://localhost:8080/fjdsfjdfj"
      }
  ],
  "category": "Spodrt",
  "seller": "Markus",
  "stock": 4,
  "reviews": []

}

### 
DELETE http://localhost:8080/api/v1/admin/products/6033df5f39385b07401a0f80