

GET http://localhost:8080/api/v1/products/

###

POST http://localhost:8080/api/v1/products/
content-type: application/json

{
  "name": "Lorem ip34324sum",
  "price": "123",
  "description": "lorem ipsum dolor sir emmet",
  "ratings": "333",
  "images": [
      {
          "public_id": "http://localhost:8080/jfdsjfjsdfjsdjfjsdfj",
          "url": "http://localhost:8080/fjdsfjdfj"
      }
  ],
  "category": "Electronic",
  "seller": "Johny",
  "stock": 424,
  "reviews": []

}

###

GET http://localhost:8080/api/v1/products/6033d69b407902059fe5b700


###


