

GET http://localhost:8080/api/v1/products


###

GET http://localhost:8080/api/v1/products?keyword=Mac&price[gte]=11&price[lte]=29

###

POST http://localhost:8080/api/v1/products/
content-type: application/json

{
  "name": "Macbook Pro 12",
  "price": "12",
  "description": "lorem ipsum dolor sir emmet",
  "ratings": "333",
  "images": [
      {
          "public_id": "http://localhost:8080/jfdsjfjsdfjsdjfjsdfj",
          "url": "http://localhost:8080/fjdsfjdfj"
      }
  ],
  "category": "Laptop",
  "seller": "Johny",
  "stock": 999,
  "reviews": []

}

###

GET http://localhost:8080/api/v1/products/60365b55d99aa80021e4824a


###

PUT http://localhost:8080/api/v1/admin/products/6033df5f39385b07401a0f80
content-type: application/json

{
  "name": "222Lem ",
  "price": "12223",
  "description": "lorem 2222ipsum dolor sir4444444444mmet worsssssddddddk",
  "images": [
      {
          "public_id": "http://localhost:8080/jfdsjfjsdfjsdjfjsdfj",
          "url": "http://localhost:8080/fjdsfjdfj"
      }
  ],
  "category": "Spodrt",
  "seller": "Markus",
  "stock": 4,
  "reviews": []

}

### 
DELETE http://localhost:8080/api/v1/admin/products/6033df5f39385b07401a0f80

### GET

PUT http://localhost:8080/api/v1/reviews
content-type: application/json

{
  "ratings": 5,
  "comment": "All fine",
  "productId": "60365b55d99aa80021e4824a"
}

###
GET http://localhost:8080/api/v1/reviews?id=60365b55d99aa80021e4824a

###

DELETE http://localhost:8080/api/v1/reviews?productId=60365b55d99aa80021e4824a&id=603a447d569d6403d4f92eba

