

POST http://localhost:8080/api/v1/register
content-type: application/json

{
 "name": "Tomas",
 "email": "john@email.com",
 "password": "password23"

}
###

POST http://localhost:8080/api/v1/login
content-type: application/json

{
 "email": "john@email.com",
 "password": "password23"

}

###

GET http://localhost:8080/api/v1/logout