

POST http://localhost:8080/api/v1/register
content-type: application/json

{
 "name": "Markus",
 "email": "markus2@gmail.com",
 "password": "qwertyuio"

}  
###

POST http://localhost:8080/api/v1/login
content-type: application/json

{
 "email": "markus2@gmail.com",
 "password": "qwertyuio"

}

###

GET http://localhost:8080/api/v1/me


###

GET http://localhost:8080/api/v1/logout

###


POST http://localhost:8080/api/v1/password/forgot
content-type: application/json

{
 "email": "tester2@gmail.com"
}

### 
PUT http://localhost:8080/api/v1/password/update
content-type: application/json

{
 "oldPassword": "test12345",
 "password": "testtest123"
}
### 
PUT http://localhost:8080/api/v1/me/update
content-type: application/json

{
    "name": "Rob",
    "email": "rob@example.com"
}
###

PUT http://localhost:8080/api/v1/password/reset/e2a9a93e120f9a7948b29f1c0a990a80c46f81cb
content-type: application/json

{
 "password": "test12345",
 "confirmPassword": "test12345"
}